inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
    - "nokogiri/demo.rb"

Metrics/ClassLength:
  Exclude:
    - "ruby-hardcoded-api/mfclient.rb"

Metrics/MethodLength:
  Exclude:
    - "homebaked/mediaflux.rb"
    - "nokogiri/mediaflux.rb"
    - "ruby-hardcoded-api/mfclient.rb"

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Enabled: false
